import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import Navbar from '../components/Navigation/Navbar'
import { ReduxProvider } from '@/redux/provider'
const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} mx-auto md:px-36 md:py-12 sm:px-12 sm:py-8 px-6 py-6`}>
        <ReduxProvider>
        <ThemeProvider attribute='class' defaultTheme="system" enableSystem>
        <Navbar/>
        {children}
        </ThemeProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}
